"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GUI.py']
DATA_FILES = [
    ('util', ['util/profile.json']),
    ('util', ['util/game_commands.json'])]
OPTIONS = {'includes': ['discord-webhook', 'pynput']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
