name: Python application

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.6
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Run tests
        run: |
          pipenv install --dev
          pipenv run pytest
